export type FormType = {
  age: string;
  chat_id: number;
  code: string;
  conditions: string;
  confirmed: boolean;
  created_at: string;
  education: string;
  gender: string;
  height: string;
  id: number;
  job: string;
  location: string;
  message_id: number;
  name: string;
  salary: string;
  type: string;
  username: string;
  weight: string;
};
